"""empty message

Revision ID: 0813c0d2d836
Revises: 615ae3e22fff
Create Date: 2018-08-02 23:00:07.666619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0813c0d2d836'
down_revision = '615ae3e22fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tokenuserd_toekn'), 'tokenuserd', ['toekn'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokenuserd_toekn'), table_name='tokenuserd')
    # ### end Alembic commands ###
