"""empty message

Revision ID: 615ae3e22fff
Revises: 
Create Date: 2018-08-02 22:59:11.469404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615ae3e22fff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokenuserd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('toekn', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokenuserd')
    # ### end Alembic commands ###
