"""empty message

Revision ID: a77227440a0d
Revises: 8f613cc2ce7b
Create Date: 2018-08-02 23:23:54.141208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a77227440a0d'
down_revision = '8f613cc2ce7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokenused',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokenused_token'), 'tokenused', ['token'], unique=False)
    op.drop_index('ix_tokenuserd_token', table_name='tokenuserd')
    op.drop_table('tokenuserd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokenuserd',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_tokenuserd_token', 'tokenuserd', ['token'], unique=False)
    op.drop_index(op.f('ix_tokenused_token'), table_name='tokenused')
    op.drop_table('tokenused')
    # ### end Alembic commands ###
